### ISSUE TITLE
TypeError: run() got an unexpected keyword argument 'no_document'

### ISSUE THREAD

**Issue by michal-h21** [papis/papis-zotero#2]
Hi,

I get the following error when I try to add a document using Zotero connector:

```
INFO:papis:zotero:server:Adding paper from zotero connector
INFO:papis:zotero:server:Checking attachment (mime text/html)
ERROR:papis:zotero:server:Not adding any attachments...
INFO:papis:zotero:server:Adding paper
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 53682)
Traceback (most recent call last):
  File "/usr/lib64/python3.6/socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python3.6/socketserver.py", line 348, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.6/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.6/socketserver.py", line 721, in __init__
    self.handle()
  File "/usr/lib64/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.6/http/server.py", line 406, in handle_one_request
    method()
  File "/usr/local/lib/python3.6/site-packages/papis_zotero/server.py", line 267, in do_POST
    self.add()
  File "/usr/local/lib/python3.6/site-packages/papis_zotero/server.py", line 247, in add
    no_document=len(files) == 0
TypeError: run() got an unexpected keyword argument 'no_document'
----------------------------------------

```
I've tried several pages like blog posts and library catalogue and this issue is the same. It seems that support for records without file attachments is broken?

**Comment by avonmoll** [comment]
Coincidentally I just tried this yesterday and had the same issue. The problem is that `papis.commands.add.run` has the following [signature](https://github.com/papis/papis/blob/97047c9a786b5ec48adbeee8e8ce9af8a6b5b6a9/papis/commands/add.py#L232):

```python
def run(
        paths,
        data=dict(),
        name=None,
        file_name=None,
        subfolder=None,
        interactive=False,
        confirm=False,
        open_file=False,
        edit=False,
        commit=False,
        link=False
        ):
```

thus there is no `no_document` argument. My guess is that it used to have that but now doesn't. Removing [this line](https://github.com/papis/papis-zotero/blob/ce398b86d24ade150a728c902142a89af0fb495d/papis_zotero/server.py#L247) fixes that issue for me. However, I'm still having trouble downloading attachments from, say, IEEEExplore. I'm not sure if it has to do with the proxy or with papis-zotero itself.

**Comment by michal-h21** [comment]
Yes, removing the `no_document` fixes the runtime error and the bibliographic record is saved by Papis. But it seems that the communication protocol used by `Zotero` translators changed, because an error popup shows in Firefox:

>  An error occurred while saving this item. See Troubleshooting Translator Issues for more information
