### ISSUE TITLE
How to sync with zotero

### ISSUE THREAD

**Issue by meicale** [papis/papis-zotero#40]
HOW to sync the papis lib with the zotero lib ?
I use zotero in windows and vscode and I use papis in wsl2/ubuntu with neovim and papis, I can import this lib export from zotero and insert it  into my text, but I cannot use pandoc to generate the file and get the error like `pandoc-citeproc: reference AScalableOptiJuYo2023 not found`. I use command `pandoc ./proposal.md --bibliography test.bib -o ./out.pdf` the test lib is just the original one. I know papis has it own lib and how to make papis share it with zotero? or how to use pandoc together with papis lib.

**Comment by alexfikl** [comment]
I'm not sure what the issue is exactly, but if you just need a BibTeX file from `papis` to feed into `pandoc`, you can use
```
papis -l <YOUR_IMPORTED_LIBRARY> export --format bibtex -o test.bib -a
```

That should work if you library was correctly imported. Unfortunately, this project just imports from Zotero, so there's no way to get the papis library and "share it with Zotero".
