### ISSUE TITLE
Papis zotero module not recognised (on mac?)

### ISSUE THREAD

**Issue by siainbuletin** [papis/papis-zotero#58]
I'm trying to install the `zotero` extension so I can import my BibTeX files to Papis. I've installed the package with the `python -m pip install papis-zotero` command, but after trying to run a simple `papis zotero`, I get this error:

```
Command 'zotero' is unknown!
Usage: papis [OPTIONS] COMMAND [ARGS]...

Error: No such command 'zotero'.
```

I don't know if this is because of how pip installs packages on my system (I'm not very well versed in the pip package manager and I see that most instructions for using papis are for Linux users).

**Comment by alexfikl** [comment]
Have you managed to fix this? I can see the issue was closed pretty quickly.

For what it's worth, `papis add --from bibtex 'zotero.bib'` should also work if you have the exported BibTeX file from Zotero. 

`papis-zotero` is mostly meant to import from the `Zotero.sqlite` database that Zotero uses directly + hook up to the Zotero connector to import directly into papis, so it's not strictly necessary.
